### ISSUE TITLE
Use this extension without API key

### ISSUE THREAD

**Issue by ElmorenohWTF** [marcelpanse/chatgpt-everywhere#6]
Would it be possible to use this extension without entering an API key? So that the use of this extension is completely free. It occurs to me that this could be done in some way, such as having the user log into the chatgpt page and using that or something similar to pass prompts and receive responses.

**Comment by marcelpanse** [comment]
Hello @ElmorenohWTF, the only way to use ChatGPT for free is by using their website. Although you can iframe the ChatGPT website on a Chrome extension, many extensions have already done this, and it will only provide you with the same ChatGPT interface but in an extension popup. 
If you wish to read and write directly from and to the input box in the extension, you need to use the API. However, there is no free way to use the API.
