### ISSUE TITLE
Issue openai api

### ISSUE THREAD

**Issue by xtofuub** [marcelpanse/chatgpt-everywhere#7]
It says "error: problem getting a response from OpenAI: you exceeded your current quota, please check your plan and billing details."
does this mean I have to pay openai for it to work why doesn't it just use chatgpt because its free

**Comment by marcelpanse** [comment]
Hi @xtofuub, chatgpt is free, but the API from openAI is not free. So to do it from an extension like this you'll need a paid OpenAI account. You only pay by actual token usage, so it will be very cheap (depending on how much you use it).
